### ISSUE TITLE
The getter 'bodyText1' isn't defined for the class 'TextTheme'

### ISSUE THREAD

**Issue by Laurens300** [sthefanoss/flutter_multi_slider#14]
pud.dev used Pana 0.22.3 to analyze this library for Flutter 3.22.0, Dart 3.4.0.
The analysis found a critical bug. This bug will cause the flutter build process to fail.

<img width="641" alt="image" src="https://github.com/sthefanoss/flutter_multi_slider/assets/10849021/bcebcd9a-82b1-4e63-9e6d-b1e8b6b7bc27"> 

Image source: https://pub.dev/packages/flutter_multi_slider/score

**Comment by sthefanoss** [comment]
@Laurens300 thanks. I'll see that today. But feel free to make a PR.

**Comment by sthefanoss** [comment]
New version will be available at https://pub.dev/packages/flutter_multi_slider soon.

**Comment by Laurens300** [comment]
> New version will be available at https://pub.dev/packages/flutter_multi_slider soon.

I am so thankful for your quick response and fix. 
We had a delivery and you really helped us out. 😁
